### ISSUE TITLE
missing python script

### ISSUE THREAD

**Issue by dpappas** [mingzhu0527/HAR#1]
Hello 

I get the following error:
python: can't open file 'norm_embed.py': [Errno 2] No such file or directory

**Comment by mingzhu0527** [comment]
I just committed a fix for it. Please pull the changes and try again.

**Comment by dpappas** [comment]
Hello! 

I still cannot find `norm_embed.py` in pinfo directory in data.
In the `run_data.sh` script there are two lines that will not run: 
```
python norm_embed.py embed_glove_d300 embed_glove_d300_norm
python norm_embed.py embed_glove_d50 embed_glove_d50_norm
```

**Comment by mingzhu0527** [comment]
Hi! I'll add them shortly after. For now, please just comment the two lines, it will still run.
